import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SiteHeader from "./components/SiteHeader";
import ThemeToggle from "./components/ThemeToggle";
// import SiteFooter from "./components/SiteFooter";

// 1. next/font/google から使いたいフォントをインポート
// import { EB_Garamond, Lato, Zen_Kaku_Gothic_New, Noto_Sans_JP } from "next/font/google";
import { EB_Garamond, Zen_Kaku_Gothic_New } from "next/font/google";
import SiteFooter from "./components/SiteFooter";

// 2. 各フォントの設定（太さや、CSSで呼び出すための変数名を指定）
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond",
});

const zenKaku = Zen_Kaku_Gothic_New({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-zen-kaku",
});

// const lato = Lato({
//   weight: ["100", "300", "400", "700", "900"],
//   style: ["normal", "italic"],
//   subsets: ["latin"],
//   variable: "--font-lato",
// });

// const notoSansJP = Noto_Sans_JP({
//   weight: ["300", "400", "500", "700"],
//   subsets: ["latin"],
//   variable: "--font-noto-sans-jp",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // OGP設定などはここに記述
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var storedTheme = localStorage.getItem('theme');
                  if (storedTheme === 'dark' || storedTheme === 'light') {
                    document.documentElement.setAttribute('data-theme', storedTheme);
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      {/* 3. bodyタグの className に、設定したフォントの変数をすべて適用する */}
      <body
        className={`${ebGaramond.variable} ${zenKaku.variable} antialiased`}
      >
        <ThemeToggle />
        <div id="container">
          <div id="container-inner">
            <SiteHeader />
            {children}
            <SiteFooter />
            {/* #container-inner */}</div>
          {/* #container */} </div>
      </body>
    </html>
  );
}
